### ISSUE TITLE
Ask for inference code

### ISSUE THREAD

**Issue by YiweiZou** [linzhiqiu/cross_modal_adaptation#6]
Great job for clip fine-tune !  Is there end-to-end inference code available to directly use the fine-tuned model for downstream tasks?

**Comment by linzhiqiu** [comment]
Thanks for asking!

In our paper, we mainly explore two modes of finetuning:
(1) **Cross-modal linear probing:** Finetune the additional linear layer on top of the CLIP encoder.
(2) **Cross-modal partial finetuning:** While finetuning the linear layer, we also unfreeze the last layer for CLIP image encoder (attention-pooling layer for CLIP-ResNet50, last transformer layer for CLIP-ViT).

Because both are very lightweight to finetune after feature extraction, we didn't release the fine-tuned model.

I would encourage you to start with cross-modal linear probe for your use case. After finetuning, you can simply append the linear layer to your CLIP encoder using torch.nn.Sequential.

Our codebase does feature extraction before training/inference for speedy experiment. If you do not want to pre-extract feature, you can easily reproduce our method following our pseudo-code. Let me know if you have any concerns/more questions.
